[package]
name = "esm-cjs-lexer"
version = "0.9.0"
description = "A WASM module to parse cjs module exports for ESM."
repository = "https://github.com/esm-dev/esm.sh"
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
anyhow = "1.0.66"
indexmap = "1.9.1"
serde = { version = "1.0.147", features = ["derive"] }

# swc
# docs: https://swc.rs
# crate: https://crates.io/search?q=swc
swc_common = { version = "0.31.17", features = ["sourcemap"] }
swc_ecmascript = { version = "0.231.14", features = ["parser", "visit"] }
swc_ecma_ast = "0.107.1"
swc_ecma_visit = "0.93.1"

# wasm-bindgen
# docs: https://rustwasm.github.io/docs/wasm-bindgen
wasm-bindgen = {version = "0.2.83", features = ["serde-serialize"]}
serde-wasm-bindgen = "0.4.5"
console_error_panic_hook = { version = "0.1.7", optional = true }
# We get build error without this
# https://docs.rs/getrandom/latest/getrandom/#webassembly-support
getrandom = { version = "0.2", features = ["js"] }

[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase (better optimization, slower build)
codegen-units = 1
# optimization for size (more aggressive)
opt-level = 'z'
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true
